// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/xingrgx/WeShareX/internal/service/internal/dao/internal"
)

// friendsDao is the data access object for table wsx_friends.
// You can define custom methods on it to extend its functionality as you wish.
type friendsDao struct {
	*internal.FriendsDao
}

var (
	// Friends is globally public accessible object for table wsx_friends operations.
	Friends = friendsDao{
		internal.NewFriendsDao(),
	}
)

// Fill with you ideas below.
