// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/xingrgx/WeShareX/internal/service/internal/dao/internal"
)

// recordDao is the data access object for table wsx_record.
// You can define custom methods on it to extend its functionality as you wish.
type recordDao struct {
	*internal.RecordDao
}

var (
	// Record is globally public accessible object for table wsx_record operations.
	Record = recordDao{
		internal.NewRecordDao(),
	}
)

// Fill with you ideas below.
