// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/xingrgx/WeShareX/internal/service/internal/dao/internal"
)

// relationDao is the data access object for table relation.
// You can define custom methods on it to extend its functionality as you wish.
type relationDao struct {
	*internal.RelationDao
}

var (
	// Relation is globally public accessible object for table relation operations.
	Relation = relationDao{
		internal.NewRelationDao(),
	}
)

// Fill with you ideas below.
