// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/xingrgx/WeShareX/internal/service/internal/dao/internal"
)

// shareDao is the data access object for table wsx_share.
// You can define custom methods on it to extend its functionality as you wish.
type shareDao struct {
	*internal.ShareDao
}

var (
	// Share is globally public accessible object for table wsx_share operations.
	Share = shareDao{
		internal.NewShareDao(),
	}
)

// Fill with you ideas below.
