// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// File is the golang structure of table wsx_file for DAO operations like Where/Data.
type File struct {
	g.Meta   `orm:"table:wsx_file, do:true"`
	Id       interface{} // 文件ID
	UserId   interface{} // 用户ID
	Name     interface{} // 文件名称
	ParentId interface{} // 父级目录ID
	Path     interface{} // 路径
	Dir      interface{} // 是否为文件夹
	CreateAt *gtime.Time // 创建时间
	UpdateAt *gtime.Time // 更新时间
	Type     interface{} // 文件类型（扩展名）
	Size     interface{} // 文件大小
	Times    interface{} // 下载次数
}
