// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Friends is the golang structure of table wsx_friends for DAO operations like Where/Data.
type Friends struct {
	g.Meta `orm:"table:wsx_friends, do:true"`
	Id     interface{} // ID
	Me     interface{} // 用户我ID
	Friend interface{} // 好友ID
	AddAt  *gtime.Time // 添加时间
	Status interface{} // 状态 同意:1 未同意:0
}
