// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Record is the golang structure of table wsx_record for DAO operations like Where/Data.
type Record struct {
	g.Meta     `orm:"table:wsx_record, do:true"`
	Id         interface{} // 聊天记录ID
	SenderId   interface{} // 发送者ID
	ReceiverId interface{} // 接收者ID
	Content    interface{} // 内容
	Time       *gtime.Time // 发送时间
}
