// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Relation is the golang structure of table wsx_relation for DAO operations like Where/Data.
type Relation struct {
	g.Meta  `orm:"table:wsx_relation, do:true"`
	Id      interface{} // ID
	ShareId interface{} // 分享ID
	FileId  interface{} // 文件ID
}
