// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Share is the golang structure of table wsx_share for DAO operations like Where/Data.
type Share struct {
	g.Meta      `orm:"table:wsx_share, do:true"`
	Id          interface{} // 分享ID
	UserId      interface{} // 用户ID
	Name        interface{} // 分享名
	UpdateTime  *gtime.Time // 更新时间
	CreateTime  *gtime.Time // 创建时间
	Code        interface{} // 提取码
	Times       interface{} // 下载次数
	NeverExpire interface{} // 1:不过期；0:过期
	ExpireTime  *gtime.Time // 过期时间
	Type        interface{} // 1:文件夹；0:文件
	FileId      interface{} // 文件文件夹ID
}
