// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// File is the golang structure for table file.
type File struct {
	Id       string      `json:"id"       description:"文件ID"`
	UserId   uint        `json:"userId"   description:"用户ID"`
	Name     string      `json:"name"     description:"文件名称"`
	ParentId string      `json:"parentId" description:"父级目录ID"`
	Path     string      `json:"path"     description:"路径"`
	Dir      int         `json:"dir"      description:"是否为文件夹"`
	CreateAt *gtime.Time `json:"createAt" description:"创建时间"`
	UpdateAt *gtime.Time `json:"updateAt" description:"更新时间"`
	Type     string      `json:"type"     description:"文件类型（扩展名）"`
	Size     int64       `json:"size"     description:"文件大小"`
	Times    int64       `json:"times"    description:"下载次数"`
}
