// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Friends is the golang structure for table friends.
type Friends struct {
	Id     int         `json:"id"     description:"ID"`
	Me     uint        `json:"me"     description:"用户我ID"`
	Friend uint        `json:"friend" description:"好友ID"`
	AddAt  *gtime.Time `json:"addAt"  description:"添加时间"`
	Status uint        `json:"status" description:"状态 同意:1 未同意:0"`
}
