// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Record is the golang structure for table record.
type Record struct {
	Id         string      `json:"id"         description:"聊天记录ID"`
	SenderId   uint        `json:"senderId"   description:"发送者ID"`
	ReceiverId uint        `json:"receiverId" description:"接收者ID"`
	Content    string      `json:"content"    description:"内容"`
	Time       *gtime.Time `json:"time"       description:"发送时间"`
}
