// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Relation is the golang structure for table relation.
type Relation struct {
	Id      string `json:"id"      description:"ID"`
	ShareId string `json:"shareId" description:"分享ID"`
	FileId  string `json:"fileId"  description:"文件ID"`
}
