// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Share is the golang structure for table share.
type Share struct {
	Id          string      `json:"id"          description:"分享ID"`
	UserId      uint        `json:"userId"      description:"用户ID"`
	Name        string      `json:"name"        description:"分享名"`
	UpdateAt    *gtime.Time `json:"updateAt"    description:"更新时间"`
	CreateAt    *gtime.Time `json:"createAt"    description:"创建时间"`
	Code        string      `json:"code"        description:"提取码"`
	Times       int         `json:"times"       description:"下载次数"`
	NeverExpire int         `json:"neverExpire" description:"1:不过期；0:过期"`
	ExpireAt    *gtime.Time `json:"expireAt"    description:"过期时间"`
	Type        int         `json:"type"        description:"1:文件夹；0:文件"`
	Nickname    string      `json:"nickname"    description:"分享者"`
}
