// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// User is the golang structure for table user.
type User struct {
	Id       int    `json:"id"       description:"UID"`
	Passport string `json:"passport" description:"账号"`
	Password string `json:"password" description:"密码"`
}
